require('./bootstrap');
require('@fortawesome/fontawesome-free');
require('admin-lte');
require('jquery-mask-plugin');
require('icheck-bootstrap');
require('overlayscrollbars/js/jquery.overlayScrollbars');
require('chart.js');
require('flot');
require('sparklines/source/sparkline');
require('jquery-knob-chif');
// require('toastr');
// require('sweetalert2');
require('ionicons');
require('datatables.net');
require('datatables.net-bs4/js/dataTables.bootstrap4');
require('bootstrap-colorpicker');
require('tempusdominus-bootstrap-4');
require("select2/dist/js/select2");
// require('bootstrap4-duallistbox');
